# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - tcb705_05_group_controller

  tcb705_05_group_controller:
    type: FollowJointTrajectory
    joints:
      - tl_robot_joint1
      - tl_robot_joint2
      - tl_robot_joint3
      - tl_robot_joint4
      - tl_robot_joint5
      - tl_robot_joint6
      - tl_robot_joint7
    action_ns: follow_joint_trajectory
    default: true