# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - armleft_group_controller
    - armright_group_controller

  armleft_group_controller:
    type: FollowJointTrajectory
    joints:
      - left_tl_robot_joint1
      - left_tl_robot_joint2
      - left_tl_robot_joint3
      - left_tl_robot_joint4
      - left_tl_robot_joint5
      - left_tl_robot_joint6
      - left_tl_robot_joint7
    action_ns: follow_joint_trajectory
    default: true
  armright_group_controller:
    type: FollowJointTrajectory
    joints:
      - right_tl_robot_joint1
      - right_tl_robot_joint2
      - right_tl_robot_joint3
      - right_tl_robot_joint4
      - right_tl_robot_joint5
      - right_tl_robot_joint6
      - right_tl_robot_joint7
    action_ns: follow_joint_trajectory
    default: true